set serveroutput on;
set verify off;

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-06 19:52:10 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE T_CLYVO_ANIMAL 
    ( 
     id_animal         NUMBER (1)  NOT NULL , 
     nm_animal         VARCHAR2 (50)  NOT NULL , 
     idade             NUMBER (10)  NOT NULL , 
     especie           VARCHAR2 (50)  NOT NULL , 
     raca              VARCHAR2 (50)  NOT NULL , 
     sexo              VARCHAR2 (1)  NOT NULL , 
     dt_nascimento     DATE  NOT NULL , 
     peso              NUMBER (10)  NOT NULL , 
     fk_id_responsavel NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE T_CLYVO_ANIMAL 
    ADD CONSTRAINT Animal_PK PRIMARY KEY ( id_animal ) ;

CREATE TABLE T_CLYVO_CONSULTA 
    ( 
     id_consulta       NUMBER (1)  NOT NULL , 
     dt_agendamento    DATE  NOT NULL , 
     dt_consulta       DATE  NOT NULL , 
     fk_id_animal      NUMBER (1)  NOT NULL , 
     fk_id_veterinario NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE T_CLYVO_CONSULTA 
    ADD CONSTRAINT Consulta_PK PRIMARY KEY ( id_consulta ) ;

CREATE TABLE T_CLYVO_DOENCA 
    ( 
     id_doenca      NUMBER (1)  NOT NULL , 
     nm_doenca      VARCHAR2 (50)  NOT NULL , 
     tipo           VARCHAR2 (50)  NOT NULL , 
     contagiosidade CHAR (1)  NOT NULL , 
     descricao      CLOB  NOT NULL 
    ) 
;

ALTER TABLE T_CLYVO_DOENCA 
    ADD CONSTRAINT doenca_PK PRIMARY KEY ( id_doenca ) ;

CREATE TABLE T_CLYVO_DOENCA_ANIMAL 
    ( 
     id_doenca_animal NUMBER (1)  NOT NULL , 
     dt_diagnostico   DATE  NOT NULL , 
     gravidade        VARCHAR2 (50)  NOT NULL , 
     status           VARCHAR2 (50)  NOT NULL , 
     observacoes      CLOB , 
     fk_id_animal     NUMBER (1) , 
     fk_id_doenca     NUMBER (1) 
    ) 
;

ALTER TABLE T_CLYVO_DOENCA_ANIMAL 
    ADD CONSTRAINT doenca_animal_PK PRIMARY KEY ( id_doenca_animal ) ;

CREATE TABLE T_CLYVO_HISTORICO 
    ( 
     id_historico         NUMBER (1)  NOT NULL , 
     Link_historico       CLOB  NOT NULL , 
     dt_criacao_historico DATE  NOT NULL , 
     num_consultas_clyvo  NUMBER (10,2)  NOT NULL , 
     fk_id_consulta       NUMBER (1)  NOT NULL , 
     fk_id_animal         NUMBER (1)  NOT NULL 
    ) 
;

ALTER TABLE T_CLYVO_HISTORICO 
    ADD CONSTRAINT Historico_PK PRIMARY KEY ( id_historico ) ;

CREATE TABLE T_CLYVO_RESPONSAVEL 
    ( 
     id_responsavel NUMBER (1)  NOT NULL , 
     nm_responsavel VARCHAR2 (50)  NOT NULL , 
     cpf            VARCHAR2 (14) , 
     dt_nascimento  DATE  NOT NULL , 
     email          VARCHAR2 (50)  NOT NULL , 
     num_celular    VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE T_CLYVO_RESPONSAVEL 
    ADD CONSTRAINT Responsavel_PK PRIMARY KEY ( id_responsavel ) ;

CREATE TABLE T_CLYVO_VACINA 
    ( 
     id_vacina NUMBER (1)  NOT NULL , 
     nm_vacina VARCHAR2 (50)  NOT NULL , 
     tipo      VARCHAR2 (50)  NOT NULL , 
     descricao CLOB NOT NULL,
     qtd_vacina NUMBER (10) NOT NULL
    ) 
;

ALTER TABLE T_CLYVO_VACINA 
    ADD CONSTRAINT Vacinas_PK PRIMARY KEY ( id_vacina ) ;

CREATE TABLE T_CLYVO_VACINA_ANIMAL 
    ( 
     id_vacina_animal NUMBER (1)  NOT NULL , 
     instrucao        CLOB  NOT NULL , 
     dt_receita       DATE  NOT NULL ,
     fk_id_vacina     NUMBER (1) , 
     fk_id_animal     NUMBER (1) 
    ) 
;

ALTER TABLE T_CLYVO_VACINA_ANIMAL 
    ADD CONSTRAINT vacina_animal_PK PRIMARY KEY ( id_vacina_animal ) ;

CREATE TABLE T_CLYVO_VETERINARIO 
    ( 
     id_veterinario NUMBER (1)  NOT NULL , 
     nm_veterinario VARCHAR2 (50)  NOT NULL , 
     cpf            VARCHAR2 (14)  NOT NULL , 
     dt_nascimento  DATE  NOT NULL , 
     email          VARCHAR2 (50) , 
     num_celular    VARCHAR2 (20)  NOT NULL , 
     especialidade  VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE T_CLYVO_VETERINARIO 
    ADD CONSTRAINT Veterinario_PK PRIMARY KEY ( id_veterinario ) ;

ALTER TABLE T_CLYVO_ANIMAL 
    ADD CONSTRAINT Animal_Responsavel_FK FOREIGN KEY 
    ( 
     fk_id_responsavel
    ) 
    REFERENCES T_CLYVO_RESPONSAVEL 
    ( 
     id_responsavel
    ) 
;

ALTER TABLE T_CLYVO_CONSULTA 
    ADD CONSTRAINT Consulta_Animal_FK FOREIGN KEY 
    ( 
     fk_id_animal
    ) 
    REFERENCES T_CLYVO_ANIMAL 
    ( 
     id_animal
    ) 
;

ALTER TABLE T_CLYVO_CONSULTA 
    ADD CONSTRAINT Consulta_Veterinario_FK FOREIGN KEY 
    ( 
     fk_id_veterinario
    ) 
    REFERENCES T_CLYVO_VETERINARIO 
    ( 
     id_veterinario
    ) 
;

ALTER TABLE T_CLYVO_DOENCA_ANIMAL 
    ADD CONSTRAINT doenca_animal_Animal_FK FOREIGN KEY 
    ( 
     fk_id_animal
    ) 
    REFERENCES T_CLYVO_ANIMAL 
    ( 
     id_animal
    ) 
;

ALTER TABLE T_CLYVO_DOENCA_ANIMAL 
    ADD CONSTRAINT doenca_animal_doenca_FK FOREIGN KEY 
    ( 
     fk_id_doenca
    ) 
    REFERENCES T_CLYVO_DOENCA 
    ( 
     id_doenca
    ) 
;

ALTER TABLE T_CLYVO_HISTORICO 
    ADD CONSTRAINT Historico_Animal_FK FOREIGN KEY 
    ( 
     fk_id_animal
    ) 
    REFERENCES T_CLYVO_ANIMAL 
    ( 
     id_animal
    ) 
;

ALTER TABLE T_CLYVO_HISTORICO 
    ADD CONSTRAINT Historico_Consulta_FK FOREIGN KEY 
    ( 
     fk_id_consulta
    ) 
    REFERENCES T_CLYVO_CONSULTA 
    ( 
     id_consulta
    ) 
;

ALTER TABLE T_CLYVO_VACINA_ANIMAL 
    ADD CONSTRAINT vacina_animal_Animal_FK FOREIGN KEY 
    ( 
     fk_id_animal
    ) 
    REFERENCES T_CLYVO_ANIMAL 
    ( 
     id_animal
    ) 
;

ALTER TABLE T_CLYVO_VACINA_ANIMAL 
    ADD CONSTRAINT vacina_animal_Vacinas_FK FOREIGN KEY 
    ( 
     fk_id_vacina
    ) 
    REFERENCES T_CLYVO_VACINA 
    ( 
     id_vacina
    ) 
;
 

-- ========================== PROCEDURE INSERTS ==========================

create or replace procedure inserir_responsavel(
    p_id_responsavel in number,
    p_nm_responsavel in varchar2,
    p_cpf in varchar2,
    p_dt_nascimento in DATE,
    p_email in varchar2,
    p_num_celular in varchar2
) 
is
begin
    insert into T_CLYVO_RESPONSAVEL (
        id_responsavel,
        nm_responsavel,
        cpf,
        dt_nascimento,
        email,
        num_celular
    ) values (
        p_id_responsavel,
        p_nm_responsavel,
        p_cpf,
        p_dt_nascimento,
        p_email,
        p_num_celular
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('Já existe um ID registrado, tente novamente!');
    when value_error then
        dbms_output.put_line('Valor inválido ou campo obrigatório não preenchido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_responsavel;
/

create or replace procedure inserir_vacina(
    p_id_vacina in number,
    p_nm_vacina in varchar2,
    p_tipo in varchar2,
    p_descricao in clob,
    p_qtd_vacina in number
)
is
begin
    insert into T_CLYVO_VACINA (
        id_vacina,
        nm_vacina,
        tipo,
        descricao,
        qtd_vacina
    ) values (
        p_id_vacina,
        p_nm_vacina,
        p_tipo,
        p_descricao,
        p_qtd_vacina
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID de vacina já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_vacina;
/

create or replace procedure inserir_veterinario(
    p_id_veterinario in number,
    p_nm_veterinario in varchar2,
    p_cpf in varchar2,
    p_dt_nascimento in date,
    p_email in varchar2,
    p_num_celular in varchar2,
    p_especialidade in varchar2
)
is
begin
    insert into T_CLYVO_VETERINARIO (
        id_veterinario,
        nm_veterinario,
        cpf,
        dt_nascimento,
        email,
        num_celular,
        especialidade
    ) values (
        p_id_veterinario,
        p_nm_veterinario,
        p_cpf,
        p_dt_nascimento,
        p_email,
        p_num_celular,
        p_especialidade
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_veterinario;
/

create or replace procedure inserir_animal(
    p_id_animal in number,
    p_nm_animal in varchar2,
    p_idade in number,
    p_especie in varchar2,
    p_raca in varchar2,
    p_sexo in varchar2,
    p_dt_nascimento in date,
    p_peso in number,
    p_id_responsavel in number
)
is
begin
    insert into T_CLYVO_ANIMAL (
        id_animal,
        nm_animal,
        idade,
        especie,
        raca,
        sexo,
        dt_nascimento,
        peso,
        fk_id_responsavel
    ) values (
        p_id_animal,
        p_nm_animal,
        p_idade,
        p_especie,
        p_raca,
        p_sexo,
        p_dt_nascimento,
        p_peso,
        p_id_responsavel
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID do animal já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_animal;
/

create or replace procedure inserir_consulta(
    p_id_consulta in number,
    p_dt_agendamento in date,
    p_dt_consulta in date,
    p_id_animal number,
    p_id_veterinario in number
)
is
begin
    insert into T_CLYVO_CONSULTA (
        id_consulta,
        dt_agendamento,
        dt_consulta,
        fk_id_animal,
        fk_id_veterinario
    ) values (
        p_id_consulta,
        p_dt_agendamento,
        p_dt_consulta,
        p_id_animal,
        p_id_veterinario
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID do consulta já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_consulta;
/

create or replace procedure inserir_vacina_animal(
    p_id_vacina_animal in number,
    p_instrucao in clob,
    p_dt_receita in date,
    p_id_vacina in number,
    p_id_animal in number
)
is
begin
    insert into T_CLYVO_VACINA_ANIMAL (
        id_vacina_animal,
        instrucao,
        dt_receita,
        fk_id_vacina,
        fk_id_animal
    ) values (
        p_id_vacina_animal,
        p_instrucao,
        p_dt_receita,
        p_id_vacina,
        p_id_animal
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID do animal já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_vacina_animal;
/

create or replace procedure inserir_doenca(
    p_id_doenca in number,
    p_nm_doenca in varchar2,
    p_tipo in varchar2,
    p_contagiosidade in char,
    p_descricao in clob
)
is
begin
    insert into T_CLYVO_DOENCA (
        id_doenca,
        nm_doenca,
        tipo,
        contagiosidade,
        descricao
    ) values (
        p_id_doenca,
        p_nm_doenca,
        p_tipo,
        p_contagiosidade,
        p_descricao
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID do vacina_animal já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_doenca;
/

create or replace procedure inserir_doenca_animal(
    p_id_doenca_animal in number,
    p_dt_diagnostico in date,
    p_gravidade in varchar2,
    p_status in varchar2,
    p_observacoes in clob,
    p_id_animal in number,
    p_id_doenca in number
)
is
begin
    insert into T_CLYVO_DOENCA_ANIMAL (
        id_doenca_animal,
        dt_diagnostico,
        gravidade,
        status,
        observacoes,
        fk_id_animal,
        fk_id_doenca
    ) values (
        p_id_doenca_animal,
        p_dt_diagnostico,
        p_gravidade,
        p_status,
        p_observacoes,
        p_id_animal,
        p_id_doenca
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID do doenca_animal já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_doenca_animal;
/

create or replace procedure inserir_doenca(
    p_id_doenca in number,
    p_nm_doenca in varchar2,
    p_tipo in varchar2,
    p_contagiosidade in char,
    p_descricao in clob
)
is
begin
    insert into T_CLYVO_DOENCA (
        id_doenca,
        nm_doenca,
        tipo,
        contagiosidade,
        descricao
    ) values (
        p_id_doenca,
        p_nm_doenca,
        p_tipo,
        p_contagiosidade,
        p_descricao
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID do vacina_animal já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_doenca;
/

create or replace procedure inserir_historico(
    p_id_historico in NUMBER,
    p_link_historico in CLOB,
    p_dt_criacao_historico in DATE,
    p_num_consultas_clyvo in NUMBER,
    p_fk_id_consulta in NUMBER,
    p_fk_id_animal in NUMBER
)
is
begin
    insert into T_CLYVO_HISTORICO(
        id_historico,
        link_historico,
        dt_criacao_historico,
        num_consultas_clyvo,
        fk_id_consulta,
        fk_id_animal
    ) values (
        p_id_historico,
        p_link_historico,
        p_dt_criacao_historico,
        p_num_consultas_clyvo,
        p_fk_id_consulta,
        p_fk_id_animal
    );

    COMMIT;

exception
    when dup_val_on_index then
        dbms_output.put_line('ID histórico já existe!');
    when value_error then
        dbms_output.put_line('Valor inválido');
    when others then
        dbms_output.put_line('Ocorreu um erro inesperado!');
end inserir_historico;
/


-- EXECUÇÃO

-- ================= INSERIR_RESPONSAVEL =================
BEGIN
    inserir_responsavel(1, 'Carlos Silva', 12345678901, DATE '1985-03-10', 'carlos@email.com', '119.999.999-99');
    inserir_responsavel(2, 'Ana Souza', 23456789012, DATE '1990-07-21', 'ana@email.com', '119.888.888-88');
    inserir_responsavel(3, 'Pedro Lima', 34567890123, DATE '1978-11-02', 'pedro@email.com', '119.777.777-77');
    inserir_responsavel(4, 'Mariana Alves', 45678901234, DATE '1995-01-15', 'mariana@email.com', '119.666.666-66');
    inserir_responsavel(5, 'João Pereira', 56789012345, DATE '1982-09-30', 'joao@email.com', '119.555.555-55');
END;
/
-- ================= INSERIR_VETERINARIO =================
BEGIN
    inserir_veterinario(1, 'Dr. Paulo', 11111111111, DATE '1970-05-20', 'paulo@vet.com', '119.111.111-11', 'Clínico Geral');
    inserir_veterinario(2, 'Dra. Fernanda', 22222222222, DATE '1980-08-12', 'fernanda@vet.com', '119.222.222-22', 'Dermatologia');
    inserir_veterinario(3, 'Dr. Ricardo', 33333333333, DATE '1975-02-28', 'ricardo@vet.com', '119.333.333-33', 'Cirurgia');
    inserir_veterinario(4, 'Dra. Juliana', 44444444444, DATE '1988-12-05', 'juliana@vet.com', '119.444.444-44', 'Cardiologia');
    inserir_veterinario(5, 'Dr. Marcos', 55555555555, DATE '1983-06-18', 'marcos@vet.com', '119.555.555-00', 'Ortopedia');
END;
/
-- ================= INSERIR_ANIMAL =================
BEGIN
    inserir_animal(1, 'Rex', 5, 'Cachorro', 'Labrador', 'M', DATE '2020-01-10', 30, 1);
    inserir_animal(2, 'Mia', 3, 'Gato', 'Siamês', 'F', DATE '2022-02-15', 5, 2);
    inserir_animal(3, 'Thor', 4, 'Cachorro', 'Bulldog', 'M', DATE '2021-06-20', 25, 3);
    inserir_animal(4, 'Luna', 2, 'Gato', 'Persa', 'F', DATE '2023-03-05', 4, 4);
    inserir_animal(5, 'Bob', 6, 'Cachorro', 'Poodle', 'M', DATE '2019-09-12', 12, 5);
END;
/

-- ================= INSERIR_CONSULTA ================= 
BEGIN
    inserir_consulta(1, DATE '2026-01-01', DATE '2026-01-02', 1, 1);
    inserir_consulta(2, DATE '2026-02-01', DATE '2026-02-02', 2, 2);
    inserir_consulta(3, DATE '2026-03-01', DATE '2026-07-02', 3, 3);
    inserir_consulta(4, DATE '2026-04-01', DATE '2026-04-02', 4, 4);
    inserir_consulta(5, DATE '2026-05-01', DATE '2026-08-02', 5, 5);
END;
/

-- ================= INSERIR_DOENCA =================
BEGIN
    inserir_doenca(1, 'Cinomose', 'Viral', 'S', 'Doença viral grave em cães');
    inserir_doenca(2, 'Raiva', 'Viral', 'S', 'Doença fatal transmissível');
    inserir_doenca(3, 'Dermatite', 'Alérgica', 'N', 'Inflamação da pele');
    inserir_doenca(4, 'Otite', 'Infecciosa', 'N', 'Infecção no ouvido');
    inserir_doenca(5, 'Parvovirose', 'Viral', 'S', 'Doença intestinal grave');
END;
/

-- ================= INSERIR_DOENCA_ANIMAL =================
BEGIN
    inserir_doenca_animal(1, DATE '2026-01-02', 'Alta', 'Em tratamento', 'Observação 1', 1, 1);
    inserir_doenca_animal(2, DATE '2026-02-02', 'Média', 'Curado', 'Observação 2', 2, 2);
    inserir_doenca_animal(3, DATE '2026-03-02', 'Baixa', 'Em tratamento', 'Observação 3', 3, 3);
    inserir_doenca_animal(4, DATE '2026-04-02', 'Alta', 'Crítico', 'Observação 4', 4, 4);
    inserir_doenca_animal(5, DATE '2026-05-02', 'Média', 'Recuperando', 'Observação 5', 5, 5);
END;
/

-- ================= INSERIR_VACINA =================
BEGIN
    inserir_vacina(1, 'Antirrábica', 'Viral', 'Protege contra raiva', 100);
    inserir_vacina(2, 'V10', 'Múltipla', 'Protege contra várias doenças', 200);
    inserir_vacina(3, 'Gripe Canina', 'Viral', 'Protege contra gripe', 150);
    inserir_vacina(4, 'Felina', 'Viral', 'Vacina para gatos', 120);
    inserir_vacina(5, 'Leishmaniose', 'Parasita', 'Proteção contra leishmaniose', 180);
END;
/

-- ================= INSERIR_VACINA_ANIMAL =================
BEGIN
    inserir_vacina_animal(1, 'Aplicar dose anual', DATE '2026-01-10', 1, 1);
    inserir_vacina_animal(2, 'Tomar com intervalo de 21 dias', DATE '2026-02-10', 2, 2);
    inserir_vacina_animal(3, 'Dose única', DATE '2026-03-10', 3, 3);
    inserir_vacina_animal(4, 'Aplicar anual', DATE '2026-04-10', 4, 4);
    inserir_vacina_animal(5, 'Reforço anual', DATE '2026-05-10', 5, 5);
END;
/

-- ================= INSERIR_HISTORICO =================
BEGIN
    inserir_historico(1, 'https://drive.google.com/file/d/abc123teste1/view', DATE '2026-01-02', 1.0, 1, 1);
    inserir_historico(2, 'https://drive.google.com/file/d/abc123teste2/view', DATE '2026-02-02', 2.0, 2, 2);
    inserir_historico(3, 'https://drive.google.com/file/d/abc123teste3/view', DATE '2026-03-02', 3.0, 3, 3);
    inserir_historico(4, 'https://drive.google.com/file/d/abc123teste4/view', DATE '2026-04-02', 4.0, 4, 4);
    inserir_historico(5, 'https://drive.google.com/file/d/abc123teste5/view', DATE '2026-05-02', 5.0, 5, 5);
END;
/


-- ========================== CONSULTAS ANONIMAS (2 BLOCOS com 3 JOINS) ==========================

-- 2: Quantidade de animais com doença contagiosa 
SELECT 
    a.especie,
    da.gravidade,
    da.status,
    da.dt_diagnostico,
    d.nm_doenca,
    d.contagiosidade
FROM T_CLYVO_ANIMAL a
JOIN T_CLYVO_DOENCA_ANIMAL da ON a.id_animal = da.fk_id_animal
JOIN T_CLYVO_DOENCA d ON da.fk_id_doenca = d.id_doenca
WHERE d.contagiosidade = 'S'
GROUP BY 
    a.especie,
    da.gravidade,
    da.status,
    da.dt_diagnostico,
    d.nm_doenca,
    d.contagiosidade
ORDER BY 
    da.dt_diagnostico DESC;


-- 2: Quantidade de animais em tratamento e em estado crítico
SELECT 
    a.especie,
    da.gravidade,
    da.status,
    da.dt_diagnostico,
    d.nm_doenca,
    d.contagiosidade
FROM T_CLYVO_DOENCA_ANIMAL da      
JOIN T_CLYVO_ANIMAL a ON da.fk_id_animal = a.id_animal 
JOIN T_CLYVO_DOENCA d ON da.fk_id_doenca = d.id_doenca
WHERE da.status = 'Em tratamento' OR da.status = 'Crítico'
GROUP BY 
    a.especie,
    da.gravidade,
    da.status,
    da.dt_diagnostico,
    d.nm_doenca,
    d.contagiosidade
ORDER BY 
    da.dt_diagnostico DESC;


-- ========================== Exercício de mostrar o próximo valor e o anterior ==========================

SELECT id_animal, nm_animal AS atual,
    NVL (LAG(nm_animal) OVER (ORDER BY id_animal), 'Vazio') AS anterior, 
    NVL(LEAD(nm_animal) OVER (ORDER BY id_animal), 'Vazio') AS proximo 
    FROM T_CLYVO_ANIMAL ORDER BY id_animal;


-- ========================== RELATORIOS ANÔNIMOS (4 BLOCOS COM CURSOR E TOMADA DE DECISÃO) ==========================

-- 1: Número de cachorros e gatos 
DECLARE
    CURSOR c_animal IS 
        SELECT especie FROM T_CLYVO_ANIMAL;
    v_num_gato NUMBER := 0;
    v_num_cachorro NUMBER := 0;
    v_especie T_CLYVO_ANIMAL.ESPECIE%TYPE;
BEGIN
    OPEN c_animal;
    LOOP 
        FETCH c_animal INTO v_especie;
        EXIT WHEN c_animal%NOTFOUND;
        IF v_especie = 'Gato' THEN
            v_num_gato := v_num_gato + 1;
        ELSIF v_especie = 'Cachorro' THEN
            v_num_cachorro := v_num_cachorro + 1;
        END IF;
    END LOOP;
    CLOSE c_animal;
    DBMS_OUTPUT.PUT_LINE('Número de gatos: ' || v_num_gato);
    DBMS_OUTPUT.PUT_LINE('Número de cachorros: ' || v_num_cachorro);
END;
/

-- 2: Consultas futuras e passadas 
DECLARE
    CURSOR c_consulta IS
        SELECT id_consulta, dt_consulta
        FROM T_CLYVO_CONSULTA;
    v_id_consulta T_CLYVO_CONSULTA.ID_CONSULTA%TYPE;
    v_dt_consulta T_CLYVO_CONSULTA.DT_CONSULTA%TYPE;
    v_dt_atual DATE := SYSDATE;
BEGIN
    OPEN c_consulta;
    LOOP
        FETCH c_consulta INTO v_id_consulta, v_dt_consulta;
        EXIT WHEN c_consulta%NOTFOUND;
        IF v_dt_consulta > v_dt_atual THEN
            DBMS_OUTPUT.PUT_LINE('Consulta ' || v_id_consulta || ' está agendada para ' || TO_CHAR(v_dt_consulta, 'DD/MM/YYYY'));
        ELSIF v_dt_consulta < v_dt_atual THEN
            DBMS_OUTPUT.PUT_LINE('Consulta ' || v_id_consulta ||' já ocorreu no dia ' || TO_CHAR(v_dt_consulta, 'DD/MM/YYYY'));
        ELSE
            DBMS_OUTPUT.PUT_LINE('Consulta ' || v_id_consulta || ' é hoje');
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Data atual: ' || TO_CHAR(v_dt_atual, 'DD/MM/YYYY'));
    CLOSE c_consulta;
END;
/

-- 3: Número de animais Macho e Fêmea 
DECLARE
    CURSOR c_animal IS 
        SELECT sexo FROM T_CLYVO_ANIMAL;
    v_num_macho NUMBER := 0;
    v_num_femea NUMBER := 0;
    v_sexo T_CLYVO_ANIMAL.SEXO%TYPE;
BEGIN
    OPEN c_animal;
    LOOP 
        FETCH c_animal INTO v_sexo;
        EXIT WHEN c_animal%NOTFOUND;
        IF v_sexo = 'M' THEN
            v_num_macho := v_num_macho + 1;
        ELSIF v_sexo = 'F' THEN
            v_num_femea := v_num_femea + 1;
        END IF;
    END LOOP;
    CLOSE c_animal;
    DBMS_OUTPUT.PUT_LINE('Número de animais do sexo masculino: ' || v_num_macho);
    DBMS_OUTPUT.PUT_LINE('Número de animais do sexo feminino: ' || v_num_femea);
END;
/

-- 4: Calcula a quantidade de vacinas "V10" aplicadas em um ano (a vacina é aplicada a cada 21 dias)

DECLARE
    v_nm_vacina VARCHAR2(50);
    v_instrucao CLOB;
    v_data_inicial DATE;
    v_data_final DATE;
    v_estoque_inicial NUMBER := 0;
    v_estoque_final NUMBER := 0;
    v_total_aplicadas NUMBER := 0;
BEGIN
    SELECT v.nm_vacina, va.instrucao, va.dt_receita, v.qtd_vacina INTO v_nm_vacina, v_instrucao, v_data_inicial, v_estoque_inicial
    FROM T_CLYVO_VACINA v JOIN T_CLYVO_VACINA_ANIMAL va ON v.id_vacina = va.fk_id_vacina
    WHERE v.nm_vacina = 'V10' AND ROWNUM = 1;

    v_data_final := ADD_MONTHS(v_data_inicial, 12);

    WHILE v_data_inicial < v_data_final LOOP
        v_total_aplicadas := v_total_aplicadas + 1;
        v_data_inicial := v_data_inicial + 21;
    END LOOP;

    v_estoque_final := v_estoque_inicial - v_total_aplicadas;

    DBMS_OUTPUT.PUT_LINE('Vacina: ' || v_nm_vacina);
    DBMS_OUTPUT.PUT_LINE('Instrução: ' || v_instrucao);
    DBMS_OUTPUT.PUT_LINE('Começo da aplicação: ' || TO_CHAR(v_data_inicial, 'DD/MM/YYYY'));
    DBMS_OUTPUT.PUT_LINE('Termino da aplicação: ' || TO_CHAR(v_data_final, 'DD/MM/YYYY'));
    DBMS_OUTPUT.PUT_LINE('Total de aplicações: ' || v_total_aplicadas);
    DBMS_OUTPUT.PUT_LINE('==============================');
    DBMS_OUTPUT.PUT_LINE('Estoque inicial: ' || v_estoque_inicial);
    DBMS_OUTPUT.PUT_LINE('Estoque final: ' || v_estoque_final);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Vacina V10 não encontrada ou sem aplicações registradas.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Ocorreu um erro inesperado: ' || SQLERRM);
END;
/
